fc /c /w 	StandardOut\depthOut_weightMap_backup.yuv Vlog\depthOut_weightMap_0.yuv >imgOutcompare.txt
fc /c /w 	StandardOut\depthOut_weightMap_backup.yuv Vlog\depthOut_weightMap_1.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\depthOut_weightMap_backup.yuv Vlog\depthOut_weightMap_2.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\depthOut_weightMap_backup.yuv Vlog\depthOut_weightMap_3.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\depthOut_weightMap_backup.yuv Vlog\depthOut_weightMap_4.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_0.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_1.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_2.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_3.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_4.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_5.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_6.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_7.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_8.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_9.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_10.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_11.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_12.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_13.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_14.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_15.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_16.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_17.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_18.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_19.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_20.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_21.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_22.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_23.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_24.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_25.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_26.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_27.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_28.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_29.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_30.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_31.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_32.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_33.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_34.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_35.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_36.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_37.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_38.yuv >>imgOutcompare.txt
fc /c /w 	StandardOut\imgOut_vdsp_backup.yuv Vlog\imgOut_vdsp_39.yuv >>imgOutcompare.txt
