adb root
adb remount
adb pull /data/log2.txt .\VLog

adb pull /data/depthOut_weightMap_0.yuv .\VLog
adb pull /data/depthOut_weightMap_1.yuv .\VLog
adb pull /data/depthOut_weightMap_2.yuv .\VLog
adb pull /data/depthOut_weightMap_3.yuv .\VLog
adb pull /data/depthOut_weightMap_4.yuv .\VLog
adb pull /data/imgOut_vdsp_0.yuv .\VLog
adb pull /data/imgOut_vdsp_1.yuv .\VLog
adb pull /data/imgOut_vdsp_2.yuv .\VLog
adb pull /data/imgOut_vdsp_3.yuv .\VLog
adb pull /data/imgOut_vdsp_4.yuv .\VLog
adb pull /data/imgOut_vdsp_5.yuv .\VLog
adb pull /data/imgOut_vdsp_6.yuv .\VLog
adb pull /data/imgOut_vdsp_7.yuv .\VLog
adb pull /data/imgOut_vdsp_8.yuv .\VLog
adb pull /data/imgOut_vdsp_9.yuv .\VLog
adb pull /data/imgOut_vdsp_10.yuv .\VLog
adb pull /data/imgOut_vdsp_11.yuv .\VLog
adb pull /data/imgOut_vdsp_12.yuv .\VLog
adb pull /data/imgOut_vdsp_13.yuv .\VLog
adb pull /data/imgOut_vdsp_14.yuv .\VLog
adb pull /data/imgOut_vdsp_15.yuv .\VLog
adb pull /data/imgOut_vdsp_16.yuv .\VLog
adb pull /data/imgOut_vdsp_17.yuv .\VLog
adb pull /data/imgOut_vdsp_18.yuv .\VLog
adb pull /data/imgOut_vdsp_19.yuv .\VLog
adb pull /data/weightMap_0.yuv .\VLog
adb pull /data/weightMap_1.yuv .\VLog
adb pull /data/weightMap_2.yuv .\VLog
adb pull /data/weightMap_3.yuv .\VLog
adb pull /data/weightMap_4.yuv .\VLog
adb pull /data/weightMap_5.yuv .\VLog
adb pull /data/weightMap_6.yuv .\VLog
adb pull /data/weightMap_7.yuv .\VLog
adb pull /data/weightMap_8.yuv .\VLog
adb pull /data/weightMap_9.yuv .\VLog
adb pull /data/weightMap_10.yuv .\VLog
adb pull /data/weightMap_11.yuv .\VLog
adb pull /data/weightMap_12.yuv .\VLog
adb pull /data/weightMap_13.yuv .\VLog
adb pull /data/weightMap_14.yuv .\VLog
adb pull /data/weightMap_15.yuv .\VLog
adb pull /data/weightMap_16.yuv .\VLog
adb pull /data/weightMap_17.yuv .\VLog
adb pull /data/weightMap_18.yuv .\VLog
adb pull /data/weightMap_19.yuv .\VLog
adb pull /data/imgOut_vdsp_20.yuv .\VLog
adb pull /data/imgOut_vdsp_21.yuv .\VLog
adb pull /data/imgOut_vdsp_22.yuv .\VLog
adb pull /data/imgOut_vdsp_23.yuv .\VLog
adb pull /data/imgOut_vdsp_24.yuv .\VLog
adb pull /data/imgOut_vdsp_25.yuv .\VLog
adb pull /data/imgOut_vdsp_26.yuv .\VLog
adb pull /data/imgOut_vdsp_27.yuv .\VLog
adb pull /data/imgOut_vdsp_28.yuv .\VLog
adb pull /data/imgOut_vdsp_29.yuv .\VLog
adb pull /data/imgOut_vdsp_30.yuv .\VLog
adb pull /data/imgOut_vdsp_31.yuv .\VLog
adb pull /data/imgOut_vdsp_32.yuv .\VLog
adb pull /data/imgOut_vdsp_33.yuv .\VLog
adb pull /data/imgOut_vdsp_34.yuv .\VLog
adb pull /data/imgOut_vdsp_35.yuv .\VLog
adb pull /data/imgOut_vdsp_36.yuv .\VLog
adb pull /data/imgOut_vdsp_37.yuv .\VLog
adb pull /data/imgOut_vdsp_38.yuv .\VLog
adb pull /data/imgOut_vdsp_39.yuv .\VLog
adb pull /data/weightMap_20.yuv .\VLog
adb pull /data/weightMap_21.yuv .\VLog
adb pull /data/weightMap_22.yuv .\VLog
adb pull /data/weightMap_23.yuv .\VLog
adb pull /data/weightMap_24.yuv .\VLog
adb pull /data/weightMap_25.yuv .\VLog
adb pull /data/weightMap_26.yuv .\VLog
adb pull /data/weightMap_27.yuv .\VLog
adb pull /data/weightMap_28.yuv .\VLog
adb pull /data/weightMap_29.yuv .\VLog
adb pull /data/weightMap_30.yuv .\VLog
adb pull /data/weightMap_31.yuv .\VLog
adb pull /data/weightMap_32.yuv .\VLog
adb pull /data/weightMap_33.yuv .\VLog
adb pull /data/weightMap_34.yuv .\VLog
adb pull /data/weightMap_35.yuv .\VLog
adb pull /data/weightMap_36.yuv .\VLog
adb pull /data/weightMap_37.yuv .\VLog
adb pull /data/weightMap_38.yuv .\VLog
adb pull /data/weightMap_39.yuv .\VLog

adb pull /data/disp.yuv .\VLog

compare.bat

